---
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.5.1
    hooks:
      - id: ruff
        args: ['--fix']
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.5.1
    hooks:
      - id: ruff-format
  - repo: https://github.com/python-poetry/poetry
    rev: '1.8.2'
    hooks:
      - id: poetry-check
      - id: poetry-lock